server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://eurekaserver:8761/eureka/

resilience4j.circuitbreaker:
  instances:
    companiesservice:
      registerHealthIndicator: true
      slidingWindowSize: 100