spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://equify@localhost:3306/equify_db
    username: equify
    password: Equ!fy
  jpa:
    hibernate:
      ddl-auto: none

  # for some reason the bootstrap.yml file is not being read, so repeating app name here temporarily
  application:
    name: dealsservice

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j.circuitbreaker:
  instances:
    companiesservice:
      registerHealthIndicator: true
      slidingWindowSize: 100