#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://equify@localhost:3306/equify_db
#    username:
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: none